### ISSUE TITLE
source map 映射有误

### ISSUE THREAD

**Issue by ImHype** [ImHype/nej-loader#6]

**Comment by q2177329q** [comment]
在使用source map时候，当denfind中有{pro}依赖时会有以下错误：
ERROR in ./src/main/webapp/src/javascript/components/pager/pager.js
Module build failed: Error: Invalid mapping: {"generated":{"line":3,"column":0},"source":"/Users/liangdequan/Desktop/netease/workspace/haitaowap/src/main/webapp/src/javascript/components/pager/pager.js","original":{"line":0,"column":0},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/liangdequan/Desktop/netease/workspace/haitaowap/node_modules/source-map/lib/source-map-generator.js:289:13)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/liangdequan/Desktop/netease/workspace/haitaowap/node_modules/source-map/lib/source-map-generator.js:101:12)
    at module.exports (/Users/liangdequan/Desktop/netease/workspace/haitaowap/node_modules/nej-loader/lib/SourceMap.js:24:19)
    at Object.nejLoader (/Users/liangdequan/Desktop/netease/workspace/haitaowap/node_modules/nej-loader/index.js:67:27)
    at applySyncOrAsync (/Users/liangdequan/Desktop/netease/workspace/haitaowap/node_modules/happypack/lib/applyLoaders.js:350:21)
    at apply (/Users/liangdequan/Desktop/netease/workspace/haitaowap/node_modules/happypack/lib/applyLoaders.js:277:5)
    at /Users/liangdequan/Desktop/netease/workspace/haitaowap/node_modules/happypack/lib/applyLoaders.js:135:7
    at applyPitchLoader (/Users/liangdequan/Desktop/netease/workspace/haitaowap/node_modules/happypack/lib/applyLoaders.js:188:14)
    at applyPitchLoader (/Users/liangdequan/Desktop/netease/workspace/haitaowap/node_modules/happypack/lib/applyLoaders.js:196:14)
    at applyPitchLoader (/Users/liangdequan/Desktop/netease/workspace/haitaowap/node_modules/happypack/lib/applyLoaders.js:196:14)
 @ ./src/main/webapp/src/javascript/components/ListComponent.js 11:4-28
 @ ./src/main/webapp/src/javascript/components ^(?!.*(?:version|demo.js$|catchkaola|demo)).*\.js$
 @ ./src/main/webapp/test/unit/index.js
